### PR TITLE
Fixing the docs

### PR DESCRIPTION
**Pull request by swarnimarun**
Thought I should fix it as I caught it.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
Thanks!

**Comment by swarnimarun** [comment]
And yes wanted to ask can I work on it to add features I want or should I help with something, I really want to have a FOSS pixel art editor that's lighter than krita.

**Comment by mitchcurtis** [comment]
Absolutely, it would be awesome to have people contributing. :D For new features it depends a lot on what you want to add, but just let me know what you're after and we can discuss it. :)

**Comment by swarnimarun** [comment]
@mitchcurtis yeah fine will do. Where should I start a conversation, create a issue?

**Comment by mitchcurtis** [comment]
Hmm, I don't have a good place for discussion at the moment... I will look into setting something up. If you have suggestions, feel free to create issues.

**Comment by swarnimarun** [comment]
@mitchcurtis As for some discussion platforms I think Discord or IRC might be good ideas.

**Comment by mitchcurtis** [comment]
It seems like you have to have a Linux server set up with Docker to host Discourse, which is more effort than I'm willing to put in. :p Discord is not a bad idea. I'd rather stay away from IRC, as I don't think it's a good, modern platform for discussion (lose any discussion while not logged in (and people who are new to it don't understand this and leave 5 minutes after asking their question), spam bots are currently flooding most channels).

**Comment by mitchcurtis** [comment]
Like I said though, feel free to create any suggestions as issues in the meantime. :)

**Comment by mitchcurtis** [comment]
Here is the invite link to the Discord server: https://discord.gg/ZtAAg5D

**Pull request merged**
