### PR TITLE
Use Qt's undo system instead of 3rdparty/qt-undo

### PR DESCRIPTION
**Pull request by bjorn**
Avoids a dependency, at least while QtWidgets is used anyway.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
Hey, thanks for the patch!

I think this makes sense, but the problem is that some properties were added to (Q)UndoStack that don't exist in Qt:

https://github.com/mitchcurtis/qt-undo/blob/master/src/undo/undostack.h#L16

I get the following errors when running Slate after applying the patch:

> qrc:/qml/ui/MenuBar.qml:124:26: Unable to assign [undefined] to bool
> qrc:/qml/ui/MenuBar.qml:131:26: Unable to assign [undefined] to bool
> qrc:/qml/ui/IconToolBar.qml:90:26: Unable to assign [undefined] to bool
> qrc:/qml/ui/IconToolBar.qml:102:26: Unable to assign [undefined] to bool

If it weren't for the missing properties in Qt, this patch would be fine in principle.

On a related note, I've [been trying](https://codereview.qt-project.org/#/c/190704/) to remove the dependency within Qt itself, but haven't had any reviews yet.

**Comment by bjorn** [comment]
> On a related note, I've been trying to remove the dependency within Qt itself, but haven't had any reviews yet.

Hmm, it's great that you tried to improve this part in Qt, but I'm not surprised about the reluctance to accept that change.

Maybe open a smaller patch to Qt adding just the properties for now? I can actually approve patches to Qt, and I don't think anybody would object to that (though unfortunately it's too late for Qt 5.9 now).

**Comment by bjorn** [comment]
What if I would change the patch to add those properties in a custom class derived from QUndoStack for now?

**Comment by mitchcurtis** [comment]
> Maybe open a smaller patch to Qt adding just the properties for now? I can actually approve patches to Qt, and I don't think anybody would object to that (though unfortunately it's too late for Qt 5.9 now).

That's not a bad idea...

> What if I would change the patch to add those properties in a custom class derived from QUndoStack for now?

If you could get that to work, I'd be fine with it. It might be tricky though, because the functions you'd need to override aren't virtual, and you'd need to e.g. emit change signals and stuff.

**Comment by mitchcurtis** [comment]
https://github.com/mitchcurtis/slate/issues/33 to track this.

**Comment by mitchcurtis** [comment]
Thanks again! I've used this as the basis for https://github.com/mitchcurtis/slate/commit/cde31ef328ed28851b662f764fe79e7cee40a3ae, which (along with the other commits on that branch) will be merged to master eventually.

**Comment by bjorn** [comment]
Thanks! Seems like Slate expanded quite a bit since I had opened this PR. :-)

**Comment by mitchcurtis** [comment]
Yeah! :D It's turned into more of a general bitmap editor which is cool.

**Pull request closed without merging**
