### PR TITLE
Take brush size into account when calculating line bounds.

### PR DESCRIPTION
**Pull request by not-surt**

### CODE REVIEW

**Comment by mitchcurtis** [comment]
Oooo, contributions! :D Thanks! I'll take a look when my brain is working.. bit late at the moment. :)

**Comment by mitchcurtis** [comment]
Thanks! From what I can see, this fixes the issue where the ends of the line are cut off? That means it partially fixes #7, coincidentally. :)

I understand everything except the square root part. Would you mind pushing an extra patch that adds a comment before that line explaining what the square root does there?

**Comment by not-surt** [comment]
sqrt(2) is just the ratio between the hypotenuse of a square and its side. A simplification of Pythagoras’ theorem.
The bound could be tighter by taking into account the specific rotation of the brush, but the sqrt(2) ensures it is big enough for any rotation.

**Comment by mitchcurtis** [comment]
Thanks!

**Pull request merged**
