### PR TITLE
Add CMakeLists

### PR DESCRIPTION
**Pull request by wow2006**
I just add CMakefile to lib,app. I am still having a problem with `import ui`.
I just make this pull request so anyone with qml import part knowledge please help.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
What's the error you're getting?

**Comment by wow2006** [comment]
I did not include QML path to cmake

the error is:
```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:30 "ui": no such directory
```

**Comment by mitchcurtis** [comment]
Just a guess, but if you're introducing a qml.qrc file for the CMake, you should probably add all of the QML files:

https://github.com/mitchcurtis/slate/pull/117/files#diff-2caf519a0386c2f35d7cac9733d7a0ba

See https://github.com/mitchcurtis/slate/blob/master/app/qml/qml.qbs for the full list.

**Comment by wow2006** [comment]
@mitchcurtis Thanks that help alot. Finally how to generate vcs-repo-state.h header I can not find rule to generate it? Chould you help me with it?

**Comment by mitchcurtis** [comment]
> @mitchcurtis Thanks that help alot.

No worries!

> Finally how to generate vcs-repo-state.h header I can not find rule to generate it? Chould you help me with it?

That's something that Qbs generates, so I see two options:

- Generate the same header with CMake (using e.g. https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable as a reference), or
- I can add a macro definition that's only defined when building with Qbs. Then when building with CMake, [this](https://github.com/mitchcurtis/slate/blob/053b2f316798370d622633a80bab438a068137d7/lib/buildinfo.cpp#L29) code will be hit.

Which one would you prefer?

**Comment by wow2006** [comment]
@mitchcurtis That works like a charm. I just generate the header using [config](http://xit0.org/2013/04/cmake-use-git-branch-and-commit-details-in-project/).

**Comment by mitchcurtis** [comment]
Great! I will test these patches out soon. :)

**Comment by mitchcurtis** [comment]
The app builds and runs without problems, which is good!

A couple of issues though:

- Tests aren't built.
- The qtquickcontrols2.conf file seems to be ignored (even though config.qrc is present in app/CMakeLists.txt).

I'm happy to merge this as an "experimental" option for building Slate though.

Thanks for the contribution!

**Pull request merged**
